### ISSUE TITLE
Не работает с WSL (предположительно)

### ISSUE THREAD

**Issue by GS11566** [Catalyst-42/writeaword#1]
Если запустить через WSL, не получается стереть ошибочный текст, я так понимаю это делает вот этот кусок кода:
```
elif code == '\x7f': # delete key
    out = out[:-1]
```
Но если я нажму на DELETE то он никак не отреагирует.

Сам код этот на строках 235-236

Если что когда я нажимаю на ESC всё закрывается как и должно, надеюсь
Backspace тоже не работает

**Comment by Catalyst-42** [comment]
Попробуйте заменить elif строку на следующую:
```python
elif code in ('KEY_BACKSPACE', chr(8), chr(127), chr(8998)): 
```

Также `\0x7f` - это backspace клавиша, а не [delete](https://en.wikipedia.org/wiki/Delete_key#cite_ref-5) (Delete правее и чуть ниже чем backspace).

Ещё вы можете вручную посмотреть коды клавиш, чтобы использовать их потом в условии с помощью этого небольшого кода. Он выводит для каждой нажатой клавиши её код в виде десятиричного числа. У меня backspace выдаёт код 127, тогда для условия проверки надо подставить chr(127) (что при переводе в строку будет `\0x7f`).

```python
import curses
from curses import wrapper

def main(screen):
    wch = chr(0)
    action = ""

    timeout = 1000
    screen.timeout(timeout)

    while 1:
        screen.clear()
        screen.addstr(f"Inputter: ord=[{ord(wch)}] input=[{action}]")
        
        # Check input
        try:
            wch = screen.get_wch()
            if isinstance(wch, str):
                action += wch
            else:
                wch = chr(0)

        except curses.error:
            wch = chr(0)

        # Parse input
        match ord(wch):
            case 127 | 8998:  # Backspace | Delete
                action = action[:-2]

            case 27:  # Escape
                break

wrapper(main)
```

**Comment by GS11566** [comment]
Спасибо большое! Оно сработало, спасибо большое вам!)

**Comment by Catalyst-42** [comment]
Отлично! Тогда добавлю этот изменённый elif как WSL fix
